import { roboto } from "@/lib/font";
import "../styles/globals.css";
import type { Metadata } from "next";
import Footer from "@/components/shared/layout/Footer";
import Brand from "@/components/shared/Brand";
import { ThemeProvider } from "@/components/shared/layout/ThemeProvider";
import Navbar from "@/components/shared/layout/Navbar";
import TopProducts from "@/components/shared/layout/TopProducts";
import Providers from "@/components/shared/layout/Provider";

export const metadata: Metadata = {
  title: "Shoperz - Home",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/logo/shoperz-white.svg",
    shortcut: "/assets/logo/shoperz-white.svg",
    apple: "/assets/logo/shoperz-white.svg",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Providers>
            <Navbar />
            {children}
            <div className="space-y-10 mt-10">
              <Brand />
              <TopProducts />
              <Footer />
            </div>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
